services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techmove-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  api:
    build:
      context: .
      dockerfile: TechMove.Api/Dockerfile
    container_name: techmove-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TechMoveDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - JwtKey=THIS_IS_A_SUPER_SECRET_KEY_12345
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - api_dataprotection:/root/.aspnet/DataProtection-Keys
    ports:
      - "5000:80"

  web:
    build:
      context: .
      dockerfile: TechMove.Web/Dockerfile
    container_name: techmove-web
    depends_on:
      api:
        condition: service_started
    environment:
      - ApiBaseUrl=http://techmove-api:80
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - web_dataprotection:/root/.aspnet/DataProtection-Keys
    ports:
      - "5001:80"

volumes:
  db_data:
  api_dataprotection:
  web_dataprotection: